// Auto-generated by Cloude — safe to delete (removed when the preview stops).
// Extends this project's own Vite config: injects API proxies (so a frontend reaches a
// backend in another folder / on WAMP) and, in remote mode, points HMR at the relay origin.
import { loadConfigFromFile, mergeConfig } from "vite";

const PROXY = {"/napai-api": {"target": "http://localhost", "changeOrigin": true}};
const REMOTE = process.env.CLOUDE_REMOTE === "1";

// Dev-only: tell the Cloude IDE which route the preview is showing (postMessage to the
// parent frame) so the chat agent can reference the page you're looking at. No-op outside
// the IDE iframe.
const cloudeRouteReporter = {
  name: "cloude-route-reporter",
  apply: "serve",
  transformIndexHtml() {
    return [{
      tag: "script",
      injectTo: "body",
      children: [
        "(function(){",
        "  function send(){ try{ parent.postMessage({ source:'cloude-preview',",
        "    route: location.pathname + location.search + location.hash }, '*'); }catch(e){} }",
        "  var ps=history.pushState; history.pushState=function(){ ps.apply(this,arguments); send(); };",
        "  var rs=history.replaceState; history.replaceState=function(){ rs.apply(this,arguments); send(); };",
        "  addEventListener('popstate', send); addEventListener('hashchange', send);",
        "  send();",
        "})();",
      ].join("\n"),
    }];
  },
};

export default async (env) => {
  let base = {};
  try {
    const loaded = await loadConfigFromFile(env, undefined, process.cwd());
    if (loaded && loaded.config) base = loaded.config;
  } catch (e) {
    console.error("[cloude] could not load the project's vite config:", e);
  }
  const server = {};
  if (Object.keys(PROXY).length) server.proxy = PROXY;
  if (REMOTE) {
    server.allowedHosts = true;
    server.hmr = { protocol: "wss", clientPort: 443, host: process.env.CLOUDE_PREVIEW_HOST || undefined };
  }
  return mergeConfig(base, { plugins: [cloudeRouteReporter], server });
};
